version: '3'

services:
  api:
    image: node:12.14
    command: bash -c "cd /var/app && yarn start"
    ports:
      - ${APP_PORT:-8080}:8080
    volumes:
      - ./backend:/var/app
    environment:
      - APP_ENV=${APP_ENVIRONMENT:-dev}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_PORT=${DB_PORT:-27017}
      - DB_HOST=${DB_HOST:-mongo}
      - DB_DATABASE=${DB_DATABASE:-db}
      - DB_DATABASE_TEST=${DB_DATABASE_TEST:-test}
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - ${DB_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - ./data/mongo:/data/db
